# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sum.
#'
#' @param x A numeric vector.
#'
#' @export
sum_cpp <- function(x) {
    .Call(`_onezero_sum_cpp`, x)
}

#' Weighted Mean.
#'
#' @param x A numeric vector.
#' @param w A numeric vector of weights.
#'
#' @export
weighted_mean <- function(x, w) {
    .Call(`_onezero_weighted_mean`, x, w)
}

